[default]

[default.security]
secret_key = "your-very-secure-random-secret-key"
algorithm = "HS256"
access_token_expire_minutes = 43200   # 30 days
refresh_token_expire_minutes = 129600  # 90 days

[default.server]
port = 8000
host = "127.0.0.1"
log_level = "info"
reload = false

[default.db]
uri = "postgresql+psycopg2://postgres:Azozazoz1@localhost:5432/smart_life_organizer2"
connect_args = {}
echo = true

[default.ai]
# You should choose which model provider you use
api_key = "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"  # OpenRouter Key
api_url = "https://openrouter.ai/api/v1/chat/completions"  # Universal endpoint for OpenRouter
model = "deepseek/deepseek-chat-v3-0324"  # Default model to use
http_referer = "http://localhost"  # Required for OpenRouter
app_title = "Smart Life Organizer"  # Optional: used for ranking in OpenRouter
temperature = 0.7
max_tokens = 2000


#