[default]

[default.security]
secret_key = "generated-secret-key-here"  # Replace with: openssl rand -hex 32
algorithm = "HS256"
access_token_expire_minutes = 43200   # 30 days
refresh_token_expire_minutes = 129600  # 90 days

[default.server]
port = 8000
host = "127.0.0.1"
log_level = "info"
reload = false

[default.db]
uri = "postgresql+psycopg2://postgres:Azozazoz1@localhost:5432/smart_life_organizer2"
connect_args = {}
echo = true

[default.ai]
# OpenRouter Configuration
provider = "openrouter"
api_key = "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"  # Will be loaded from environment variables
api_url = "https://openrouter.ai/api/v1/chat/completions"
model = "deepseek/deepseek-chat-v3-0324"  # Updated to current recommended model

# Required Headers (will be constructed programmatically)
http_referer = "http://localhost:3000"
app_title = "Smart Life Organizer"

# Model Parameters
temperature = 0.4  # Good default for balanced responses
max_tokens = 500  # Appropriate for most use cases
#stream = false     # Good for non-streaming (set true for real-time)













